version: 2
updates:
  - package-ecosystem: gomod
    directory: /ecr-login
    schedule:
      interval: daily

  # Dependencies listed in .github/workflows/*.yml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
