version: 0.2

phases:
  install:
    commands:
      - chmod +x -R scripts
      - ./scripts/hack/codepipeline-git-commit.sh
      - ./scripts/hack/symlink-gopath-codebuild.sh
      - cd /go/src/github.com/awslabs/amazon-ecr-credential-helper
  pre_build:
    commands:
      - echo "Starting tests..."
      - make test
  build:
    commands:
      - echo "Starting build..."
      - make all-variants
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  files:
      - '**/*'
  base-directory: 'bin'
