.\" Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
.\"
.\" Licensed under the Apache License, Version 2.0 (the
.\" "License"). You may not use this file except in compliance
.\" with the License. A copy of the License is located at
.\"
.\"      http://aws.amazon.com/apache2.0/
.\"
.\" or in the "license" file accompanying this file. This file is
.\" distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
.\" CONDITIONS OF ANY KIND, either express or implied. See the
.\" License for the specific language governing permissions and
.\" limitations under the License.
.TH DOCKER-CREDENTIAL-ECR-LOGIN 1 2018-10-29 AMAZON-WEB-SERVICES AMAZON-ECR
.SH NAME
docker\-credential\-ecr\-login \- Amazon ECR Credential Helper for Docker
.SH SYNOPSYS
.B docker\-credential\-ecr\-login
COMMAND

.B docker\-credential\-ecr\-login
-v
.SH DESCRIPTION
The Amazon ECR Credential Helper for Docker is a credential helper for the
.BR docker (1)
command that makes it easier to use Amazon Elastic Container Registry.
.SH USAGE
Place the
.B docker\-credential\-ecr\-login
binary on your
.IR PATH
and set the contents of your
.IR ~/.docker/config.json
to be

.nf
{
  "credsStore":"ecr-login"
}
.fi

With Docker 1.13.0 or greater, you can configure Docker to use different
credential helpers for different registries.  To use this credential helper for
a specific ECR registry, create a
.IR credsHelper
section with the URI of your ECR registry:

.nf
{
  "credHelpers": {
    "aws_account_id.dkr.ecr.region.amazonaws.com":"ecr-login"
  }
}
.fi

Once installed, you may use \fIdocker pull\fP and \fIdocker push\fP with ECR
repositories, without running \fIdocker login\fP.
.SH AWS CREDENTIALS
The credential helper reads AWS credentials from standard locations, including
environment variables, the shared credentials file (\fI~/.aws/credentials\fP),
EC2 instance profiles, and ECS task roles.

To use credentials associated with a different named profile in the shared
credentials file, you may set the \fIAWS_PROFILE\fP environment variable.

To use credentials from an assumed role, you must set the
\fIAWS_SDK_LOAD_CONFIG\fP environment variable to \fItrue\fP.
.SH OPTIONS
.TP 16
.BR -v
Print the version and git commit used to build docker\-credential\-ecr\-login
.SH COMMANDS
.TP 16
.BR get
Retrieve credentials for a specific Amazon ECR registry. The registry should be
passed to the credential helper via
.BR stdin (3)
and results will be printed to
.BR stdout (3)
.TP 16
.BR list
Retrieve the names of each registry currently known to the helper. The helper
will cache the names of all requested registries and return them here.
.TP 16
.BR version
Return the version of the credential helper protocol implemented by this helper
.TP 16
.BR store
This command is not implemented and is a no-op.
.TP 16
.BR erase
This command is not implemented and is a no-op.
.SH COPYRIGHT
Copyright 2018 Amazon.com, Inc. or its affiliates.  All rights reserved.
.SH LICENSE
Licensed under the Apache License, version 2.0.

